FROM mcr.microsoft.com/mssql/server:2017-latest
        ENV ACCEPT_EULA=Y
        ENV SA_PASSWORD=Shiv@angi1Sing
        ENV MSSQL_PID=Developer
        ENV MSSQL_TCP_PORT=1433
        WORKDIR /src
        USER root
        RUN (/opt/mssql/bin/sqlservr --accept-eula & ) | grep -q "Service Broker manager has started" &&  /opt/mssql-tools/bin/sqlcmd -S127.0.0.1 -Usa -PShiv@angi1Sing
