FROM mcr.microsoft.com/mssql/rhel/server:2022-latest
ENV MSSQL_SA_PASSWORD=Shiv@angi1Sing
ENV ACCEPT_EULA=Y
EXPOSE 1433
USER root
RUN chmod -R 777 /opt
USER root
RUN (/opt/mssql/bin/sqlservr --accept-eula & ) | grep -q "Service Broker manager has started" &&  /opt/mssql-tools/bin/sqlcmd -S127.0.0.1 -Usa -PShiv@angi1Sing
