FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS build

WORKDIR /src
COPY ["Producer.csproj", "./"]
COPY Setup.sh Setup.sh

RUN dotnet tool install dotnet-ef

RUN dotnet restore "./Producer.csproj"
COPY . .
WORKDIR "/src/."

RUN /root/.dotnet/tools/dotnet-ef migrations add InitialMigrations

RUN chmod +x ./Setup.sh
CMD /bin/bash ./Setup.sh